### ISSUE TITLE
Request urls

### ISSUE THREAD

**Issue by mmontone** [charJe/cl-yxorp#1]
I'd like to map different urls to different ports. Say "/api" to port 9090, and "/admin" to port 9091.

I only see inspection of headers in code, not url.

Is what I want to do possible?

Thanks

**Comment by mmontone** [comment]
Mm..I see `:uri` in headers. I'll try with that ...

**Comment by charJe** [comment]
Yes, you will have to parse it to get the port. Is that okay, or do you have an idea for a better interface?

**Comment by mmontone** [comment]
Hi. I don't know. This is the first time I try this project. I let you know if a better interface occurs to me.

Another thing: actually, apart from forwarding to a different port, I would like to change the url in the process.

I'd like my `/admin/foo` map to `localhost:<adminport>/foo` (without the `admin` part). Is that possible?

**Comment by charJe** [comment]
Try `(setf (yxorp:header :uri) "new uri")` in the request filter.

**Comment by mmontone** [comment]
Oh. Thank you very much for your help!

**Comment by mmontone** [comment]
It is working :D

**Comment by mmontone** [comment]
Here I paste what I'm doing as reference:

```lisp
(yxorp:start 
 (yxorp:config :port 9400
	       :destinator (lambda ()
			     (cond
			       ((str:starts-with? "/admin" (yxorp:header :uri))
				(access:accesses *config* :admin :port))
			       ((str:starts-with? "/web" (yxorp:header :uri))
				(access:accesses *config* :web :port))
			       ((str:starts-with? "/api" (yxorp:header :uri))
				(access:accesses *config* :api :port))))
	       :request-filter (lambda (x)
				 (flet ((remove-url-prefix (prefix)
					  (setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length prefix)))))
				   (cond
				     ((str:starts-with? "/admin" (yxorp:header :uri))
				      (remove-url-prefix "/admin"))
				     ((str:starts-with? "/web" (yxorp:header :uri))
				      (remove-url-prefix "/web"))
				     ((str:starts-with? "/api" (yxorp:header :uri))
				      (remove-url-prefix "/api")))
				   ))))
```

There's probably a better, more concise way to code it, but this does the job.

**Comment by charJe** [comment]
I know I said request-filter before, but you should be able to set the uri in the destinator. That way, you do not need to duplicate your cond tests.

**Comment by charJe** [comment]
Also note that the return value of the request-filter is the body sent to the server, so in this case, the body from the client (x) is lost and replaced with new uri. I think this is not quite what you were going for.

**Comment by mmontone** [comment]
Ah. I see. I'll change that code. I think it is working somehow, though.

Thanks.

**Comment by mmontone** [comment]
This is definitively working :smile: 

```lisp
(yxorp:start 
 (yxorp:config :port 9400
	       :destinator (lambda ()
			     (cond
			       ((str:starts-with? "/admin" (yxorp:header :uri))
				(setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length "/admin")))
				(access:accesses *config* :admin :port))
			       ((str:starts-with? "/web" (yxorp:header :uri))
				(setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length "/web")))
				(access:accesses *config* :web :port))
			       ((str:starts-with? "/api" (yxorp:header :uri))
				(setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length "/api")))
				(access:accesses *config* :api :port))))))

```

Thanks again

**Comment by charJe** [comment]
```lisp
(defmacro endpoint-redirect (&body endpoints)
  (let ((gensyms (loop repeat (length endpoints) collect (gensym))))
    `(let (,@(mapcar 'list gensyms endpoints))
       (cond
        ,@(mapcar (lambda (endpoint)
                    `((str:starts-with? ,endpoint (yxorp:header :uri))
		      (setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length ,endpoint)))
                      (access:accesses *config*
                                       (alexandria:make-keyword (str:upcase (subseq ,endpoint 1)))
                                       :port)))
                  gensyms)))))

(endpoint-redirect
  "/admin"
  "/web"
  "/api")
```

**Comment by mmontone** [comment]
Oh, yeah! I was not as inspired as you are :smile: 

It is great to have this project. I'll probably be using it quite a lot when developing web services in Lisp.

**Comment by mmontone** [comment]
One last iteration, I think I'd prefer to do it like this, have `(url-prefix port)` as endpoint setting, so that it is generic and doesn't not get tied to how I'm doing configurations:

```lisp
(defmacro endpoint-redirect (&body endpoints)
  `(cond
     ,@(mapcar (lambda (endpoint)
                 `((str:starts-with? ,(first endpoint) (yxorp:header :uri))
		   (setf (yxorp:header :uri) (subseq (yxorp:header :uri) (length ,(first endpoint)))) 
                  ,(second endpoint)))
               endpoints)))

(endpoint-redirect
  ("/admin" (access:accesses *config* :admin :port))
  ("/web" (access:accesses *config* :web :port))
  ("/api" (access:accesses *config* :api :port)))
```

Cheers,
