### ISSUE TITLE
How do I forward https? 

### ISSUE THREAD

**Issue by freddyholms** [charJe/cl-yxorp#4]
On my local network, I have some ssl acceptor on say machine 192.168.162.10:8000, If in my config I write something simple in `:destinator` like `(lambda () ("192.168.162.10:8000"))`, I get a barrage of errors of the form
```
Error while processing connection: A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X7F448C057BF0) (SSL_get_error: 1). ERR_print_errors(): 139932562650880:error:1408F09C:SSL routines:ssl3_get_record:http request:../ssl/record/ssl3_record.c:321
```
Which is the same behavior I see if I access http://192.168.162.10:8000. Maybe I don't understand the library very well, but is reverse proxying https possible? I used to be able to do this in nginx with proxy_pass.

**Comment by charJe** [comment]
I don't think it is currently possible. A destination is currently just a host and a port, would you like it to include the protocol as well? This might be difficult with websocket since the destination for a websocket look the same as one for http, but they are different protocols.

**Comment by freddyholms** [comment]
That would be nice, would it be difficult to implement?

**Comment by charJe** [comment]
I should be able to do it, but I'm not sure what the interface should be.

Option 1: Put http:// or https:// in front. Omission means http. It would also have to work for ws:// and wss://.

Option 2: Keep the interface the same, but handle this ssl error by retrying with an ssl connection.

Option 3: Somehow specify the desire for an ssl connection without specifying the actual protocol.

I am open to other options too.

**Comment by freddyholms** [comment]
I would be partial to option 1, that seems like the most intuitive choice that leaves full control to the user.

**Comment by charJe** [comment]
Hey, could you try out this branch https://github.com/charJe/cl-yxorp/tree/forward-to-ssl. Let me know how it works for you.

**Comment by freddyholms** [comment]
I am testing the branch but I ran into a problem. I set up a hunchentoot ssl acceptor on port 8080 using
```
(defvar acceptor (make-instance 'hunchentoot:easy-ssl-acceptor 
                                                     :port 8080 
                                                     :ssl-privatekey-file "./domain-keys.pem" 
                                                     :ssl-certificate-file "./cert.pem"))
```
This acceptor works as I can reach the website in my browser by going to my-domain.com:8080. I configured yxorp with
```
(defvar *yxorp-config* (yxorp:config
			  :port 443
			  :destinator ;; function to decide where to forward requests
			  (lambda ()
			    "https://127.0.0.1:8080")
			  :ssl (yxorp:ssl-config ;; enable ssl
				:certificate "./cert.pem" ;; path to the cert file
				:key  "./domain-keys.pem" ;; path to the key file
				:redirect-port 80 ;; port to expect HTTP connections and redirect to HTTPS
				:redirect-to 443)))
```
But when trying to connect to my-domain.com, I get the error
`SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY`

If I replace my acceptor with the http variant and make the corresponding change to *yxorp-config* I get the desired behavior. Is there something wrong with my configuration?

**Comment by charJe** [comment]
I ran into this as well. Your yxorp configuration looks good. I think it is a configuration problem for cl+ssl. See this issue: https://github.com/cl-plus-ssl/cl-plus-ssl/pull/150.

I fixed it by running these two lines: 
```lisp
(cl+ssl:ensure-initialized) ; needed to set the *ssl-global-context* 
(cl+ssl::ssl-ctx-set-verify-location cl+ssl::*ssl-global-context* "/etc/ssl/certs/")
```

**Comment by freddyholms** [comment]
Thanks, it is working now. Will this branch be merged into master?

**Comment by charJe** [comment]
I think I managed to make the changes without any breaking changes, so I will get on that.

**Comment by charJe** [comment]
I pushed it to master. I'll close this issue now.
